name: Tauri Build (tag + branch + manual)

on:
  push:
    branches:
      - ci/tauri-build-test
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      - name: Install Tauri CLI
        run: npm install --no-save @tauri-apps/cli-win32-x64-msvc

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Tauri target
        uses: actions/cache@v4
        with:
          path: src-tauri/target
          key: ${{ runner.os }}-tauri-target-${{ hashFiles('src-tauri/Cargo.lock') }}

      - name: Build Windows EXE
        run: npm run tauri:build:exe

      - name: Upload Windows EXE artifact only
        uses: actions/upload-artifact@v4
        with:
          name: BiliBili-History-Frontend.exe
          path: BiliBili-History-Frontend.exe
          if-no-files-found: error


